name: CI/CD NGINX Moni Challenge

on:
  push:
    paths:
      - "index.html"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Iniciar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Iniciar sesión en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nginx-moni:latest